name: Build and populate cache

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 3" # 03:00 on Wednesday, this is beacuse we want to update 1hr after the inputs update

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          logger: pretty

      - name: Setup cachix
        uses: cachix/cachix-action@v13
        with:
          name: everviolet
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build from the matrix
        run: nix build -L
